default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sales_managment_system_development
  username: postgres
  password: meowmerry03
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: sales_managment_system_test
  username: postgres
  password: meowmerry03
  host: 127.0.0.1 
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: sales_management_production
  username: sales_management_production_user
  password: <%= ENV['DATABASE_PASSWORD'] || 'GbOqsglxKoWqxW4bxDMUDjhbLMqX1nAE' %>
  host: dpg-ct0g7056l47c73b4qn20-a
  port: 5432
