default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sales_managment_system_development
  username: postgres
  password: meowmerry03
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: sales_managment_system_test
  username: postgres
  password: meowmerry03
  host: 127.0.0.1  # Update this line to point to localhost
  port: 5432

production:
  <<: *default
  database: sales_managment_system_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
