default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sales_managment_system_development
  username: postgres
  password: meowmerry03
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: sales_managment_system_test
  username: postgres
  password: meowmerry03
  host: 127.0.0.1 
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  sslmode: require
  prepare_statements: false
  advisory_locks: false
