version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: meowmerry03
      POSTGRES_DB: sales_management_system_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  rails:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000' # Expose Rails backend on port 3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:meowmerry03@db/sales_management_system_development
    command: ['rails', 'server', '-b', '0.0.0.0']
    networks:
      - sales_network

  # Optional: Add a separate service for the React frontend (if running it independently)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    # command: bash -c "cd frontend && npm start"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - '5000:5000' # Expose React app on port 3001 (React runs on port 3000 by default)
    depends_on:
      - rails
    networks:
      - sales_network

volumes:
  postgres_data:

networks:
  sales_network:
    driver: bridge
