databases:
  - name: sales_management_db
    databaseName: sales_management_db
    user: sales_management
    plan: free

services:
  - type: web
    name: sales-management-system
    runtime: ruby
    rootDir: backend
    buildCommand: bundle install && bundle exec rake db:migrate
    startCommand: bundle exec rails server -p $PORT -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sales_management_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /health