services:
  - type: web
    name: sales-management-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        value: postgresql://sales_management_production_user:GbOqsglxKoWqxW4bxDMUDjhbLMqX1nAE@dpg-ct0g7056l47c73b4qn20-a/sales_management_production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_PASSWORD
        value: GbOqsglxKoWqxW4bxDMUDjhbLMqX1nAE

  - type: web
    name: sales-management-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn preview --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        value: https://sales-management-backend.onrender.com
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

databases:
  - name: sales_management_db
    databaseName: sales_management_production
    user: sales_management_production_user
    plan: free
