services:
  - type: web
    name: sales-management-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        value: postgres://sales_management_production_user:GbOqsglxKoWqxW4bxDMUDjhbLMqX1nAE@dpg-ct0gbh8gph6c739llfb0-a.oregon-postgres.render.com/sales_management_production
      - key: RAILS_MASTER_KEY
        value: 37688b56bde617604ad1c986cf06fa1e
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: POSTGRES_SSLMODE
        value: "require"
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: sales-management-frontend
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn preview --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_URL
        value: https://sales-management-backend.onrender.com
      - key: NODE_ENV
        value: production
    autoDeploy: true

databases:
  - name: sales_management_db
    databaseName: sales_management_production
    user: sales_management_production_user
    plan: free
    ipAllowList: []
