source "https://rubygems.org"
ruby "3.3.0"

# Specify the Rails version
gem "rails", "~> 7.0.8"

# Use Puma web server
gem "puma", ">= 5.0"

# Database
gem "pg", "~> 1.1"

# Performance and caching
gem "bootsnap", require: false

# API and CORS
gem "rack-cors"

# System dependencies
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Development and test gems
group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end