source "https://rubygems.org"
ruby "3.3.6"

# Specify the Rails version
gem "rails", "~> 7.0.0"

# Use Puma web server
gem "puma", ">= 5.0"

# Database
gem "pg", "~> 1.1"

# Performance and caching
gem "bootsnap", require: false

# API and CORS
gem "rack-cors"

# Assets and frontend
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

# System dependencies
gem "tzinfo-data"
gem "mutex_m"
gem "base64"
gem "bigdecimal"

# Production specific gems
group :production do
  gem 'redis', '~> 4.0'
end

# Development and test gems
group :development, :test do
  gem "byebug"
  gem "brakeman", require: false
  gem "rubocop-rails", require: false
end