default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: meowmerry03
  host: 127.0.0.1

development:
  <<: *default
  database: sales_management_system_development

test:
  <<: *default
  database: sales_management_system_test

production:
  <<: *default
  database: sales_management_system_production
  username: <%= ENV['SALES_MANAGEMENT_SYSTEM_DATABASE_USERNAME'] %>
  password: <%= ENV['SALES_MANAGEMENT_SYSTEM_DATABASE_PASSWORD'] %>